#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

// tbd if this is better.
enum class topt : uint8_t {
	keep, // keep type and decorations
	keep_type, // keep only type
	overloads,
	template_,
	ptr,
	ref,
	const_ptr,
	const_ref,
	take_address,
	to_last_param,
	reg_to_cpp, // required for __m* to cpp overloads
	cast,
	bool_,
	f32,
	f64,
	i8,
	u8,
	i16,
	u16,
	i32,
	u32,
	i64,
	u64,
	count,
};

struct intrin_desc {
	std::string intrin_name;
	std::string func_name;
	std::vector<topt> return_opts;
	std::vector<std::vector<topt>> arg_opts;
	bool m32bits = false;
	bool commented = false;
};

#define ss_suffix "_s"
#define sd_suffix "_s"
#define si_suffix "_s"
#define ps1_suffix "_p1"
#define pd1_suffix "_p1"

inline const std::vector<intrin_desc> intrin_descriptions{
	// mmx
	intrin_desc{
			.intrin_name = "_mm_add_pi16",
			.func_name = "add",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
			// all mmx functions are 32bits
	},
	intrin_desc{
			.intrin_name = "_mm_add_pi32",
			.func_name = "add",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_add_pi8",
			.func_name = "add",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_adds_pi16",
			.func_name = "adds",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_adds_pi8",
			.func_name = "adds",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_adds_pu16",
			.func_name = "adds",
			.return_opts{ topt::u16 },
			.arg_opts{ { topt::u16 }, { topt::u16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_adds_pu8",
			.func_name = "adds",
			.return_opts{ topt::u8 },
			.arg_opts{ { topt::u8 }, { topt::u8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_and_si64",
			.func_name = "and_",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_andnot_si64",
			.func_name = "andnot",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpeq_pi16",
			.func_name = "cmpeq",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpeq_pi32",
			.func_name = "cmpeq",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpeq_pi8",
			.func_name = "cmpeq",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpgt_pi16",
			.func_name = "cmpgt",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpgt_pi32",
			.func_name = "cmpgt",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpgt_pi8",
			.func_name = "cmpgt",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtm64_si64",
			.func_name = "cvt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i64 } },
			.commented = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsi32_si64",
			.func_name = "cvt_s2s",
			.return_opts{ topt::i64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsi64_m64",
			.func_name = "cvt_s2s",
			.return_opts{ topt::i64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
			.commented = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsi64_si32",
			.func_name = "cvt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_empty",
			.func_name = "empty",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_madd_pi16",
			.func_name = "madd",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_mulhi_pi16",
			.func_name = "mulhi",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_mullo_pi16",
			.func_name = "mulhi",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_or_si64",
			.func_name = "or_",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_packs_pi16",
			.func_name = "packs",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_packs_pi32",
			.func_name = "packs",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_packs_pu16",
			.func_name = "packs",
			.return_opts{ topt::u8 },
			.arg_opts{ { topt::u16 }, { topt::u16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_set_pi16",
			.func_name = "set",
			.return_opts{ topt::i16, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_set_pi32",
			.func_name = "set",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_set_pi8",
			.func_name = "set",
			.return_opts{ topt::i8, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_set1_pi16",
			.func_name = "set1",
			.return_opts{ topt::i16, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_set1_pi32",
			.func_name = "set1",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_set1_pi8",
			.func_name = "set1",
			.return_opts{ topt::i8, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_setr_pi16",
			.func_name = "setr",
			.return_opts{ topt::i16, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_setr_pi32",
			.func_name = "setr",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_setr_pi8",
			.func_name = "setr",
			.return_opts{ topt::i8, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_setzero_si64",
			.func_name = "setzero",
			.return_opts{ topt::overloads, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_sll_pi16",
			.func_name = "sll",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sll_pi32",
			.func_name = "sll",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sll_si64",
			.func_name = "sll",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_slli_pi16",
			.func_name = "slli",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_slli_pi32",
			.func_name = "slli",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_slli_si64",
			.func_name = "slli",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_sra_pi16",
			.func_name = "sra",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sra_pi32",
			.func_name = "sra",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_srai_pi16",
			.func_name = "srai",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_srai_pi32",
			.func_name = "srai",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_srl_pi16",
			.func_name = "srl",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_srl_pi32",
			.func_name = "srl",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_srl_si64",
			.func_name = "srl",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_srli_pi16",
			.func_name = "srli",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_srli_pi32",
			.func_name = "srli",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_srli_si64",
			.func_name = "srli",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_sub_pi16",
			.func_name = "sub",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sub_pi32",
			.func_name = "sub",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sub_pi8",
			.func_name = "sub",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_subs_pi16",
			.func_name = "subs",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_subs_pi8",
			.func_name = "subs",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_subs_pu16",
			.func_name = "subs",
			.return_opts{ topt::u16 },
			.arg_opts{ { topt::u16 }, { topt::u16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_subs_pu8",
			.func_name = "subs",
			.return_opts{ topt::u8 },
			.arg_opts{ { topt::u8 }, { topt::u8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpackhi_pi16",
			.func_name = "unpackhi",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpackhi_pi32",
			.func_name = "unpackhi",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpackhi_pi8",
			.func_name = "unpackhi",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpacklo_pi16",
			.func_name = "unpacklo",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpacklo_pi32",
			.func_name = "unpacklo",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpacklo_pi8",
			.func_name = "unpacklo",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_xor_si64",
			.func_name = "xor_",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
	},

	// ignored
	intrin_desc{ .intrin_name = "_m_empty" },
	intrin_desc{ .intrin_name = "_m_from_int" },
	intrin_desc{ .intrin_name = "_m_from_int64" },
	intrin_desc{ .intrin_name = "_m_packssdw" },
	intrin_desc{ .intrin_name = "_m_packsswb" },
	intrin_desc{ .intrin_name = "_m_packuswb" },
	intrin_desc{ .intrin_name = "_m_paddb" },
	intrin_desc{ .intrin_name = "_m_paddd" },
	intrin_desc{ .intrin_name = "_m_paddsb" },
	intrin_desc{ .intrin_name = "_m_paddsw" },
	intrin_desc{ .intrin_name = "_m_paddusb" },
	intrin_desc{ .intrin_name = "_m_paddusw" },
	intrin_desc{ .intrin_name = "_m_paddw" },
	intrin_desc{ .intrin_name = "_m_pand" },
	intrin_desc{ .intrin_name = "_m_pandn" },
	intrin_desc{ .intrin_name = "_m_pcmpeqb" },
	intrin_desc{ .intrin_name = "_m_pcmpeqd" },
	intrin_desc{ .intrin_name = "_m_pcmpeqw" },
	intrin_desc{ .intrin_name = "_m_pcmpgtb" },
	intrin_desc{ .intrin_name = "_m_pcmpgtd" },
	intrin_desc{ .intrin_name = "_m_pcmpgtw" },
	intrin_desc{ .intrin_name = "_m_pmaddwd" },
	intrin_desc{ .intrin_name = "_m_pmulhw" },
	intrin_desc{ .intrin_name = "_m_pmullw" },
	intrin_desc{ .intrin_name = "_m_por" },
	intrin_desc{ .intrin_name = "_m_pslld" },
	intrin_desc{ .intrin_name = "_m_pslldi" },
	intrin_desc{ .intrin_name = "_m_psllq" },
	intrin_desc{ .intrin_name = "_m_psllqi" },
	intrin_desc{ .intrin_name = "_m_psllw" },
	intrin_desc{ .intrin_name = "_m_psllwi" },
	intrin_desc{ .intrin_name = "_m_psrad" },
	intrin_desc{ .intrin_name = "_m_psradi" },
	intrin_desc{ .intrin_name = "_m_psraw" },
	intrin_desc{ .intrin_name = "_m_psrawi" },
	intrin_desc{ .intrin_name = "_m_psrld" },
	intrin_desc{ .intrin_name = "_m_psrldi" },
	intrin_desc{ .intrin_name = "_m_psrlq" },
	intrin_desc{ .intrin_name = "_m_psrlqi" },
	intrin_desc{ .intrin_name = "_m_psrlw" },
	intrin_desc{ .intrin_name = "_m_psrlwi" },
	intrin_desc{ .intrin_name = "_m_psubb" },
	intrin_desc{ .intrin_name = "_m_psubd" },
	intrin_desc{ .intrin_name = "_m_psubsb" },
	intrin_desc{ .intrin_name = "_m_psubsw" },
	intrin_desc{ .intrin_name = "_m_psubusb" },
	intrin_desc{ .intrin_name = "_m_psubusw" },
	intrin_desc{ .intrin_name = "_m_psubw" },
	intrin_desc{ .intrin_name = "_m_punpckhbw" },
	intrin_desc{ .intrin_name = "_m_punpckhdq" },
	intrin_desc{ .intrin_name = "_m_punpckhwd" },
	intrin_desc{ .intrin_name = "_m_punpcklbw" },
	intrin_desc{ .intrin_name = "_m_punpckldq" },
	intrin_desc{ .intrin_name = "_m_punpcklwd" },
	intrin_desc{ .intrin_name = "_m_pxor" },
	intrin_desc{ .intrin_name = "_m_to_int" },
	intrin_desc{ .intrin_name = "_m_to_int64" },

	// sse
	intrin_desc{
			.intrin_name = "_mm_add_ps",
			.func_name = "add",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_add_ss",
			.func_name = "add" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_and_ps",
			.func_name = "and_",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_andnot_ps",
			.func_name = "andnot",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_avg_pu16",
			.func_name = "avg",
			.return_opts{ topt::u16 },
			.arg_opts{ { topt::u16 }, { topt::u16 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_avg_pu8",
			.func_name = "avg",
			.return_opts{ topt::u8 },
			.arg_opts{ { topt::u8 }, { topt::u8 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cmpeq_ps",
			.func_name = "cmpeq",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpeq_ss",
			.func_name = "cmpeq" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpge_ps",
			.func_name = "cmpge",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpge_ss",
			.func_name = "cmpge" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpgt_ps",
			.func_name = "cmpgt",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpgt_ss",
			.func_name = "cmpgt" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmple_ps",
			.func_name = "cmple",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmple_ss",
			.func_name = "cmple" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmplt_ps",
			.func_name = "cmplt",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmplt_ss",
			.func_name = "cmplt" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpneq_ps",
			.func_name = "cmpneq",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpneq_ss",
			.func_name = "cmpneq" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpnge_ps",
			.func_name = "cmpnge",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpnge_ss",
			.func_name = "cmpnge" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpngt_ps",
			.func_name = "cmpngt",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpngt_ss",
			.func_name = "cmpngt" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpnle_ps",
			.func_name = "cmpnle",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpnle_ss",
			.func_name = "cmpnle" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpnlt_ps",
			.func_name = "cmpnlt",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpnlt_ss",
			.func_name = "cmpnlt" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpord_ps",
			.func_name = "cmpord",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpord_ss",
			.func_name = "cmpord" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpunord_ps",
			.func_name = "cmpunord",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpunord_ss",
			.func_name = "cmpunord" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_comieq_ss",
			.func_name = "comieq",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_comige_ss",
			.func_name = "comige",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_comigt_ss",
			.func_name = "comigt",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_comile_ss",
			.func_name = "comile",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_comilt_ss",
			.func_name = "comilt",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_comineq_ss",
			.func_name = "comineq",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtpi16_ps",
			.func_name = "cvt_p2p",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i16 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtpi32_ps",
			.func_name = "cvt_p2p",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 }, { topt::i32 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtpi32x2_ps",
			.func_name = "cvt_px22p",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtpi8_ps",
			.func_name = "cvt_p2p",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i8 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtps_pi16",
			.func_name = "cvt_p2p",
			.return_opts{ topt::i16, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtps_pi32",
			.func_name = "cvt_p2p",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtps_pi8",
			.func_name = "cvt_p2p",
			.return_opts{ topt::i8, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtpu16_ps",
			.func_name = "cvt_p2p",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::u16 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtpu8_ps",
			.func_name = "cvt_p2p",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::u8 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsi32_ss",
			.func_name = "cvt_s2s",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 }, { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsi64_ss",
			.func_name = "cvt_s2s",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 }, { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtss_f32",
			.func_name = "cvt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtss_si32",
			.func_name = "cvt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtss_si64",
			.func_name = "cvt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvttps_pi32",
			.func_name = "cvtt_p2p",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvttss_si32",
			.func_name = "cvtt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvttss_si64",
			.func_name = "cvtt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_div_ps",
			.func_name = "div",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_div_ss",
			.func_name = "div" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_extract_pi16",
			.func_name = "extract",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::i16 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_free",
			.func_name = "free",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_MM_GET_EXCEPTION_MASK",
			.func_name = "get_exception_mask",
			.return_opts{ topt::keep },
			.arg_opts{},
	},
	intrin_desc{
			.intrin_name = "_MM_GET_EXCEPTION_STATE",
			.func_name = "get_exception_state",
			.return_opts{ topt::keep },
			.arg_opts{},
	},
	intrin_desc{
			.intrin_name = "_MM_GET_FLUSH_ZERO_MODE",
			.func_name = "get_flush_zero_mode",
			.return_opts{ topt::keep },
			.arg_opts{},
	},
	intrin_desc{
			.intrin_name = "_MM_GET_ROUNDING_MODE",
			.func_name = "get_rounding_mode",
			.return_opts{ topt::keep },
			.arg_opts{},
	},
	intrin_desc{
			.intrin_name = "_mm_getcsr",
			.func_name = "getcsr",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_insert_pi16",
			.func_name = "insert",
			.return_opts{ topt::i16 },
			.arg_opts{
					{ topt::i16 },
					{ topt::keep },
					{ topt::keep, topt::template_ },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_load_ps",
			.func_name = "load",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_load_ps1",
			.func_name = "load" ps1_suffix,
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep_type, topt::const_ref, topt::take_address } },
	},
	intrin_desc{
			.intrin_name = "_mm_load_ss",
			.func_name = "load" ss_suffix,
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep_type, topt::const_ref, topt::take_address } },
	},
	intrin_desc{
			.intrin_name = "_mm_load1_ps",
			.func_name = "load1",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep_type, topt::const_ref, topt::take_address } },
	},
	intrin_desc{
			.intrin_name = "_mm_loadh_pi",
			.func_name = "loadh",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::f32 },
					{ topt::f32, topt::const_ptr, topt::reg_to_cpp },
			},
			//.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_loadl_pi",
			.func_name = "loadl",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::f32 },
					{ topt::f32, topt::const_ptr, topt::reg_to_cpp },
			},
			//.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_loadr_ps",
			.func_name = "loadr",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_loadu_ps",
			.func_name = "loadu",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_malloc",
			.func_name = "malloc",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep }, { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_maskmove_si64",
			.func_name = "maskmove",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::overloads },
					{ topt::u8 },
					{ topt::overloads, topt::ptr, topt::to_last_param },
			},
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_max_pi16",
			.func_name = "max",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_max_ps",
			.func_name = "max",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_max_pu8",
			.func_name = "max",
			.return_opts{ topt::u8 },
			.arg_opts{ { topt::u8 }, { topt::u8 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_max_ss",
			.func_name = "max" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_min_pi16",
			.func_name = "min",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_min_ps",
			.func_name = "min",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_min_pu8",
			.func_name = "min",
			.return_opts{ topt::u8 },
			.arg_opts{ { topt::u8 }, { topt::u8 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_min_ss",
			.func_name = "min" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_move_ss",
			.func_name = "move" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_movehl_ps",
			.func_name = "movehl",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_movelh_ps",
			.func_name = "movelh",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_movemask_pi8",
			.func_name = "movemask",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::i8 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_movemask_ps",
			.func_name = "movemask",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_mul_ps",
			.func_name = "mul",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_mul_ss",
			.func_name = "mul" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_mulhi_pu16",
			.func_name = "mulhi",
			.return_opts{ topt::u16 },
			.arg_opts{ { topt::u16 }, { topt::u16 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_or_ps",
			.func_name = "or_",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_prefetch",
			.func_name = "prefetch",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::keep },
					{ topt::keep, topt::template_ },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_rcp_ps",
			.func_name = "rcp",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_rcp_ss",
			.func_name = "rcp" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_rsqrt_ps",
			.func_name = "rsqrt",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_rsqrt_ss",
			.func_name = "rsqrt" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sad_pu8",
			.func_name = "sad",
			.return_opts{ topt::u16 },
			.arg_opts{ { topt::u8 }, { topt::u8 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_MM_SET_EXCEPTION_MASK",
			.func_name = "set_exception_mask",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_MM_SET_EXCEPTION_STATE",
			.func_name = "set_exception_state",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_MM_SET_FLUSH_ZERO_MODE",
			.func_name = "set_flush_zero_mode",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_set_ps",
			.func_name = "set",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_set_ps1",
			.func_name = "set" ps1_suffix,
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_MM_SET_ROUNDING_MODE",
			.func_name = "set_rounding_mode",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_set_ss",
			.func_name = "set" ss_suffix,
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_set1_ps",
			.func_name = "set1",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_setcsr",
			.func_name = "setcsr",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_setr_ps",
			.func_name = "setr",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_setzero_ps",
			.func_name = "setzero",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_sfence",
			.func_name = "sfence",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_shuffle_pi16",
			.func_name = "shuffle",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_shuffle_ps",
			.func_name = "shuffle",
			.return_opts{ topt::f32 },
			.arg_opts{
					{ topt::f32 },
					{ topt::f32 },
					{ topt::keep, topt::template_ },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_sqrt_ps",
			.func_name = "sqrt",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sqrt_ss",
			.func_name = "sqrt" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_store_ps",
			.func_name = "store",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::keep, topt::to_last_param },
					{ topt::f32 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_store_ps1",
			.func_name = "store" ps1_suffix,
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::keep, topt::to_last_param },
					{ topt::f32 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_store_ss",
			.func_name = "store" ss_suffix,
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::keep_type, topt::ref, topt::take_address,
							topt::to_last_param },
					{ topt::f32 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_store1_ps",
			.func_name = "store1",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::keep, topt::to_last_param },
					{ topt::f32 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_storeh_pi",
			.func_name = "storeh",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::f32, topt::ptr, topt::to_last_param,
							topt::reg_to_cpp },
					{ topt::f32 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_storel_pi",
			.func_name = "storel",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::f32, topt::ptr, topt::to_last_param,
							topt::reg_to_cpp },
					{ topt::f32 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_storer_ps",
			.func_name = "storer",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::keep, topt::to_last_param },
					{ topt::f32 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_storeu_ps",
			.func_name = "storeu",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::keep, topt::to_last_param },
					{ topt::f32 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_stream_pi",
			.func_name = "stream",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::f32, topt::ptr, topt::to_last_param },
					{ topt::f32 },
			},
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_stream_ps",
			.func_name = "stream",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::keep, topt::to_last_param },
					{ topt::f32 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_sub_ps",
			.func_name = "sub",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sub_ss",
			.func_name = "sub" ss_suffix,
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_MM_TRANSPOSE4_PS",
			.func_name = "transpose4",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::f32 },
					{ topt::f32 },
					{ topt::f32 },
					{ topt::f32 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_ucomieq_ss",
			.func_name = "ucomieq",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_ucomige_ss",
			.func_name = "ucomige",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_ucomigt_ss",
			.func_name = "ucomigt",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_ucomile_ss",
			.func_name = "ucomile",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_ucomilt_ss",
			.func_name = "ucomilt",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_ucomineq_ss",
			.func_name = "ucomineq",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_undefined_ps",
			.func_name = "undefined",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpackhi_ps",
			.func_name = "unpackhi",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpacklo_ps",
			.func_name = "unpacklo",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_xor_ps",
			.func_name = "xor_",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},

	// ignored
	intrin_desc{ .intrin_name = "_m_maskmovq" },
	intrin_desc{ .intrin_name = "_m_pavgb" },
	intrin_desc{ .intrin_name = "_m_pavgw" },
	intrin_desc{ .intrin_name = "_m_pextrw" },
	intrin_desc{ .intrin_name = "_m_pinsrw" },
	intrin_desc{ .intrin_name = "_m_pmaxsw" },
	intrin_desc{ .intrin_name = "_m_pmaxub" },
	intrin_desc{ .intrin_name = "_m_pminsw" },
	intrin_desc{ .intrin_name = "_m_pminub" },
	intrin_desc{ .intrin_name = "_m_pmovmskb" },
	intrin_desc{ .intrin_name = "_m_pmulhuw" },
	intrin_desc{ .intrin_name = "_m_psadbw" },
	intrin_desc{ .intrin_name = "_m_pshufw" },
	intrin_desc{ .intrin_name = "_mm_cvt_pi2ps" },
	intrin_desc{ .intrin_name = "_mm_cvt_ps2pi" },
	intrin_desc{ .intrin_name = "_mm_cvt_si2ss" },
	intrin_desc{ .intrin_name = "_mm_cvt_ss2si" },
	intrin_desc{ .intrin_name = "_mm_cvtt_ps2pi" },
	intrin_desc{ .intrin_name = "_mm_cvtt_ss2si" },

	// sse2
	intrin_desc{
			.intrin_name = "_mm_add_epi16",
			.func_name = "add",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_add_epi32",
			.func_name = "add",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_add_epi64",
			.func_name = "add",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_add_epi8",
			.func_name = "add",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_add_pd",
			.func_name = "add",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_add_sd",
			.func_name = "add" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_add_si64",
			.func_name = "add",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_adds_epi16",
			.func_name = "adds",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_adds_epi8",
			.func_name = "adds",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_adds_epu16",
			.func_name = "adds",
			.return_opts{ topt::u16 },
			.arg_opts{ { topt::u16 }, { topt::u16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_adds_epu8",
			.func_name = "adds",
			.return_opts{ topt::u8 },
			.arg_opts{ { topt::u8 }, { topt::u8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_and_pd",
			.func_name = "and_",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_and_si128",
			.func_name = "and_",
			.return_opts{ topt::overloads },
			.arg_opts{ { topt::overloads }, { topt::overloads } },
	},
	intrin_desc{
			.intrin_name = "_mm_andnot_pd",
			.func_name = "andnot",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_andnot_si128",
			.func_name = "andnot",
			.return_opts{ topt::overloads },
			.arg_opts{ { topt::overloads }, { topt::overloads } },
	},
	intrin_desc{
			.intrin_name = "_mm_avg_epu16",
			.func_name = "avg",
			.return_opts{ topt::u16 },
			.arg_opts{ { topt::u16 }, { topt::u16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_avg_epu8",
			.func_name = "avg",
			.return_opts{ topt::u8 },
			.arg_opts{ { topt::u8 }, { topt::u8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_bslli_si128",
			.func_name = "bslli",
			.return_opts{ topt::overloads },
			.arg_opts{
					{ topt::overloads },
					{ topt::keep, topt::template_ },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_bsrli_si128",
			.func_name = "bsrli",
			.return_opts{ topt::overloads },
			.arg_opts{
					{ topt::overloads },
					{ topt::keep, topt::template_ },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_castpd_ps",
			.func_name = "cast",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_castpd_si128",
			.func_name = "cast",
			.return_opts{ topt::overloads, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_castps_pd",
			.func_name = "cast",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_castps_si128",
			.func_name = "cast",
			.return_opts{ topt::overloads, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_castsi128_pd",
			.func_name = "cast",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::overloads } },
	},
	intrin_desc{
			.intrin_name = "_mm_castsi128_ps",
			.func_name = "cast",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::overloads } },
	},
	intrin_desc{
			.intrin_name = "_mm_clflush",
			.func_name = "clflush",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpeq_epi16",
			.func_name = "cmpeq",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpeq_epi32",
			.func_name = "cmpeq",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpeq_epi8",
			.func_name = "cmpeq",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpeq_pd",
			.func_name = "cmpeq",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpeq_sd",
			.func_name = "cmpeq" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpge_pd",
			.func_name = "cmpge",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpge_sd",
			.func_name = "cmpge" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpgt_epi16",
			.func_name = "cmpgt",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpgt_epi32",
			.func_name = "cmpgt",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpgt_epi8",
			.func_name = "cmpgt",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpgt_pd",
			.func_name = "cmpgt",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpgt_sd",
			.func_name = "cmpgt" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmple_pd",
			.func_name = "cmple",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmple_sd",
			.func_name = "cmple" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmplt_epi16",
			.func_name = "cmplt",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmplt_epi32",
			.func_name = "cmplt",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmplt_epi8",
			.func_name = "cmplt",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmplt_pd",
			.func_name = "cmplt",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmplt_sd",
			.func_name = "cmplt" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpneq_pd",
			.func_name = "cmpneq",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpneq_sd",
			.func_name = "cmpneq" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpnge_pd",
			.func_name = "cmpnge",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpnge_sd",
			.func_name = "cmpnge" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpngt_pd",
			.func_name = "cmpngt",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpngt_sd",
			.func_name = "cmpngt" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpnle_pd",
			.func_name = "cmpnle",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpnle_sd",
			.func_name = "cmpnle" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpnlt_pd",
			.func_name = "cmpnlt",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpnlt_sd",
			.func_name = "cmpnlt" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpord_pd",
			.func_name = "cmpord",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpord_sd",
			.func_name = "cmpord" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpunord_pd",
			.func_name = "cmpunord",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cmpunord_sd",
			.func_name = "cmpunord" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_comieq_sd",
			.func_name = "comieq",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_comige_sd",
			.func_name = "comige",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_comigt_sd",
			.func_name = "comigt",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_comile_sd",
			.func_name = "comile",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_comilt_sd",
			.func_name = "comilt",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_comineq_sd",
			.func_name = "comineq",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtepi32_pd",
			.func_name = "cvt_p2p",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtepi32_ps",
			.func_name = "cvt_p2p",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtpd_epi32",
			.func_name = "cvt_p2p",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtpd_pi32",
			.func_name = "cvt_p2p",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtpd_ps",
			.func_name = "cvt_p2p",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtpi32_pd",
			.func_name = "cvt_p2p",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i32 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvtps_epi32",
			.func_name = "cvt_p2p",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtps_pd",
			.func_name = "cvt_p2p",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsd_f64",
			.func_name = "cvt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsd_si32",
			.func_name = "cvt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsd_si64",
			.func_name = "cvt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsd_ss",
			.func_name = "cvt_s2s",
			.return_opts{ topt::f32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsi128_si32",
			.func_name = "cvt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsi128_si64",
			.func_name = "cvt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsi32_sd",
			.func_name = "cvt_s2s",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 }, { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsi32_si128",
			.func_name = "cvt_s2s",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsi64_sd",
			.func_name = "cvt_s2s",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 }, { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtsi64_si128",
			.func_name = "cvt_s2s",
			.return_opts{ topt::i64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvtss_sd",
			.func_name = "cvt_s2s",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvttpd_epi32",
			.func_name = "cvtt_p2p",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvttpd_pi32",
			.func_name = "cvtt_p2p",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_cvttps_epi32",
			.func_name = "cvtt_p2p",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvttsd_si32",
			.func_name = "cvtt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_cvttsd_si64",
			.func_name = "cvtt_s2s",
			.return_opts{ topt::keep, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_div_pd",
			.func_name = "div",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_div_sd",
			.func_name = "div" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_extract_epi16",
			.func_name = "extract",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::i16 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_insert_epi16",
			.func_name = "extract",
			.return_opts{ topt::i16 },
			.arg_opts{
					{ topt::i16 },
					{ topt::keep },
					{ topt::keep, topt::template_ },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_lfence",
			.func_name = "lfence",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_load_pd",
			.func_name = "load",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_load_pd1",
			.func_name = "load" pd1_suffix,
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep_type, topt::const_ref, topt::take_address } },
	},
	intrin_desc{
			.intrin_name = "_mm_load_sd",
			.func_name = "load" sd_suffix,
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep_type, topt::const_ref, topt::take_address } },
	},
	intrin_desc{
			.intrin_name = "_mm_load_si128",
			.func_name = "load",
			.return_opts{ topt::overloads, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::overloads, topt::const_ptr, topt::reg_to_cpp } },
	},
	intrin_desc{
			.intrin_name = "_mm_load1_pd",
			.func_name = "load1",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep_type, topt::const_ref, topt::take_address } },
	},
	intrin_desc{
			.intrin_name = "_mm_loadh_pd",
			.func_name = "loadh",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 }, { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_loadl_epi64",
			.func_name = "loadl",
			.return_opts{ topt::i64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i64, topt::const_ptr, topt::reg_to_cpp } },
	},
	intrin_desc{
			.intrin_name = "_mm_loadl_pd",
			.func_name = "loadl",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::f64 }, { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_loadr_pd",
			.func_name = "loadr",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_loadu_pd",
			.func_name = "loadu",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_loadu_si128",
			.func_name = "loadu",
			.return_opts{ topt::overloads, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::overloads, topt::const_ptr, topt::reg_to_cpp } },
	},
	intrin_desc{
			.intrin_name = "_mm_loadu_si16",
			.func_name = "loadu" si_suffix,
			.return_opts{ topt::i16, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i16, topt::const_ref, topt::take_address } },
	},
	intrin_desc{
			.intrin_name = "_mm_loadu_si32",
			.func_name = "loadu" si_suffix,
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i32, topt::const_ref, topt::take_address } },
	},
	intrin_desc{
			.intrin_name = "_mm_loadu_si64",
			.func_name = "loadu" si_suffix,
			.return_opts{ topt::i64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i64, topt::const_ref, topt::take_address } },
	},
	intrin_desc{
			.intrin_name = "_mm_madd_epi16",
			.func_name = "madd",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_maskmoveu_si128",
			.func_name = "maskmoveu",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::overloads },
					{ topt::u8 },
					{ topt::overloads, topt::ptr, topt::cast,
							topt::to_last_param },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_max_epi16",
			.func_name = "max",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_max_epu8",
			.func_name = "max",
			.return_opts{ topt::u8 },
			.arg_opts{ { topt::u8 }, { topt::u8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_max_pd",
			.func_name = "max",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_max_sd",
			.func_name = "max" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_mfence",
			.func_name = "mfence",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_min_epi16",
			.func_name = "min",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_min_epu8",
			.func_name = "min",
			.return_opts{ topt::u8 },
			.arg_opts{ { topt::u8 }, { topt::u8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_min_pd",
			.func_name = "min",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_min_sd",
			.func_name = "min" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_move_epi64",
			.func_name = "move",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_move_sd",
			.func_name = "move" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_movemask_epi8",
			.func_name = "movemask",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_movemask_pd",
			.func_name = "movemask",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_movepi64_pi64",
			.func_name = "mov",
			.return_opts{ topt::i64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i64 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_movpi64_epi64",
			.func_name = "mov",
			.return_opts{ topt::i64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::i64 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_mul_epu32",
			.func_name = "mul" si_suffix,
			.return_opts{ topt::u64 },
			.arg_opts{ { topt::u32 }, { topt::u32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_mul_pd",
			.func_name = "mul",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_mul_sd",
			.func_name = "mul" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_mul_su32",
			.func_name = "mul" si_suffix,
			.return_opts{ topt::u64 },
			.arg_opts{ { topt::u32 }, { topt::u32 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_mulhi_epi16",
			.func_name = "mulhi",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_mulhi_epu16",
			.func_name = "mulhi",
			.return_opts{ topt::u16 },
			.arg_opts{ { topt::u16 }, { topt::u16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_mullo_epi16",
			.func_name = "mullo",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_or_pd",
			.func_name = "or_",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_or_si128",
			.func_name = "or_",
			.return_opts{ topt::overloads },
			.arg_opts{ { topt::overloads }, { topt::overloads } },
	},
	intrin_desc{
			.intrin_name = "_mm_packs_epi16",
			.func_name = "packs",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_packs_epi32",
			.func_name = "packs",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_packus_epi16",
			.func_name = "packus",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_pause",
			.func_name = "pause",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_sad_epu8",
			.func_name = "sad",
			.return_opts{ topt::u16 },
			.arg_opts{ { topt::u8 }, { topt::u8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_set_epi16",
			.func_name = "set",
			.return_opts{ topt::i16, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_set_epi32",
			.func_name = "set",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_set_epi64x",
			.func_name = "set",
			.return_opts{ topt::i64, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_set_epi8",
			.func_name = "set",
			.return_opts{ topt::i8, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_set_pd",
			.func_name = "set",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_set_pd1",
			.func_name = "set" pd1_suffix,
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_set_sd",
			.func_name = "set" sd_suffix,
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_set1_epi16",
			.func_name = "set1",
			.return_opts{ topt::i16, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_set1_epi32",
			.func_name = "set1",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_set1_epi64x",
			.func_name = "set1",
			.return_opts{ topt::i64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_set1_epi8",
			.func_name = "set1",
			.return_opts{ topt::i8, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_set1_pd",
			.func_name = "set1",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_setr_epi16",
			.func_name = "setr",
			.return_opts{ topt::i16, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_setr_epi32",
			.func_name = "setr",
			.return_opts{ topt::i32, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_setr_epi64",
			.func_name = "setr",
			.return_opts{ topt::i64, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::i64 },
					{ topt::i64 },
			},
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_setr_epi8",
			.func_name = "setr",
			.return_opts{ topt::i8, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_setr_pd",
			.func_name = "setr",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{
					{ topt::keep },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_setzero_pd",
			.func_name = "setzero",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_setzero_si128",
			.func_name = "setzero",
			.return_opts{ topt::overloads, topt::ref, topt::to_last_param },
			.arg_opts{},
	},
	intrin_desc{
			.intrin_name = "_mm_shuffle_epi32",
			.func_name = "shuffle",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_shuffle_pd",
			.func_name = "shuffle",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 },
					{ topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_shufflehi_epi16",
			.func_name = "shufflehi",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_shufflelo_epi16",
			.func_name = "shufflelo",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_sll_epi16",
			.func_name = "sll",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sll_epi32",
			.func_name = "sll",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sll_epi64",
			.func_name = "sll",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_slli_epi16",
			.func_name = "slli",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_slli_epi32",
			.func_name = "slli",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_slli_epi64",
			.func_name = "slli",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_sqrt_pd",
			.func_name = "sqrt",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sqrt_sd",
			.func_name = "sqrt" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sra_epi16",
			.func_name = "sra",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sra_epi32",
			.func_name = "sra",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_srai_epi16",
			.func_name = "srai",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_srai_epi32",
			.func_name = "srai",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_srl_epi16",
			.func_name = "srl",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_srl_epi32",
			.func_name = "srl",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_srl_epi64",
			.func_name = "srl",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_srli_epi16",
			.func_name = "srli",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_srli_epi32",
			.func_name = "srli",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_srli_epi64",
			.func_name = "srli",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::keep, topt::template_ } },
	},
	intrin_desc{
			.intrin_name = "_mm_store_pd",
			.func_name = "store",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep, topt::to_last_param }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_store_pd1",
			.func_name = "store" pd1_suffix,
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep, topt::to_last_param }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_store_sd",
			.func_name = "store" sd_suffix,
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::keep_type, topt::ref, topt::take_address,
							topt::to_last_param },
					{ topt::f64 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_store_si128",
			.func_name = "store",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::overloads, topt::ptr, topt::reg_to_cpp,
							topt::to_last_param },
					{ topt::overloads },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_store1_pd",
			.func_name = "store1",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep, topt::to_last_param }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_storeh_pd",
			.func_name = "storeh",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep, topt::to_last_param }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_storel_epi64",
			.func_name = "storel",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::i64, topt::ptr, topt::reg_to_cpp,
							topt::to_last_param },
					{ topt::i64 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_storel_pd",
			.func_name = "storel",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep, topt::to_last_param }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_storer_pd",
			.func_name = "storer",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep, topt::to_last_param }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_storeu_pd",
			.func_name = "storeu",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep, topt::to_last_param }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_storeu_si128",
			.func_name = "storeu",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::overloads, topt::ptr, topt::reg_to_cpp,
							topt::to_last_param },
					{ topt::overloads },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_storeu_si16",
			.func_name = "storeu" si_suffix,
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::i16, topt::ref, topt::take_address,
							topt::to_last_param },
					{ topt::i16 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_storeu_si32",
			.func_name = "storeu" si_suffix,
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::i32, topt::ref, topt::take_address,
							topt::to_last_param },
					{ topt::i32 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_storeu_si64",
			.func_name = "storeu" si_suffix,
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::i64, topt::ref, topt::take_address,
							topt::to_last_param },
					{ topt::i64 },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_stream_pd",
			.func_name = "stream",
			.return_opts{ topt::keep },
			.arg_opts{ { topt::keep, topt::to_last_param }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_stream_si128",
			.func_name = "stream",
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::overloads, topt::ptr, topt::reg_to_cpp,
							topt::to_last_param },
					{ topt::overloads },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_stream_si32",
			.func_name = "stream" si_suffix,
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::keep_type, topt::ref, topt::take_address,
							topt::to_last_param },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_stream_si64",
			.func_name = "stream" si_suffix,
			.return_opts{ topt::keep },
			.arg_opts{
					{ topt::keep_type, topt::ref, topt::take_address,
							topt::to_last_param },
					{ topt::keep },
			},
	},
	intrin_desc{
			.intrin_name = "_mm_sub_epi16",
			.func_name = "sub",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sub_epi32",
			.func_name = "sub",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sub_epi64",
			.func_name = "sub",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sub_epi8",
			.func_name = "sub",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sub_pd",
			.func_name = "sub",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sub_sd",
			.func_name = "sub" sd_suffix,
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_sub_si64",
			.func_name = "sub",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
			.m32bits = true,
	},
	intrin_desc{
			.intrin_name = "_mm_subs_epi16",
			.func_name = "subs",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_subs_epi8",
			.func_name = "subs",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_subs_epu16",
			.func_name = "subs",
			.return_opts{ topt::u16 },
			.arg_opts{ { topt::u16 }, { topt::u16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_subs_epu8",
			.func_name = "subs",
			.return_opts{ topt::u8 },
			.arg_opts{ { topt::u8 }, { topt::u8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_ucomieq_sd",
			.func_name = "ucomieq",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_ucomige_sd",
			.func_name = "ucomige",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_ucomigt_sd",
			.func_name = "ucomigt",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_ucomile_sd",
			.func_name = "ucomile",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_ucomilt_sd",
			.func_name = "ucomilt",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_ucomineq_sd",
			.func_name = "ucomineq",
			.return_opts{ topt::bool_ },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_undefined_pd",
			.func_name = "undefined",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_undefined_si128",
			.func_name = "undefined",
			.return_opts{ topt::overloads, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpackhi_epi16",
			.func_name = "unpackhi",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpackhi_epi32",
			.func_name = "unpackhi",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpackhi_epi64",
			.func_name = "unpackhi",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpackhi_epi8",
			.func_name = "unpackhi",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpackhi_pd",
			.func_name = "unpackhi",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpacklo_epi16",
			.func_name = "unpacklo",
			.return_opts{ topt::i16 },
			.arg_opts{ { topt::i16 }, { topt::i16 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpacklo_epi32",
			.func_name = "unpacklo",
			.return_opts{ topt::i32 },
			.arg_opts{ { topt::i32 }, { topt::i32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpacklo_epi64",
			.func_name = "unpacklo",
			.return_opts{ topt::i64 },
			.arg_opts{ { topt::i64 }, { topt::i64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpacklo_epi8",
			.func_name = "unpacklo",
			.return_opts{ topt::i8 },
			.arg_opts{ { topt::i8 }, { topt::i8 } },
	},
	intrin_desc{
			.intrin_name = "_mm_unpacklo_pd",
			.func_name = "unpacklo",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_xor_pd",
			.func_name = "xor_",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_xor_si128",
			.func_name = "xor_",
			.return_opts{ topt::overloads },
			.arg_opts{ { topt::overloads }, { topt::overloads } },
	},

	// ignored
	intrin_desc{ .intrin_name = "_mm_cvtsd_si64x" },
	intrin_desc{ .intrin_name = "_mm_cvtsi128_si64x" },
	intrin_desc{ .intrin_name = "_mm_cvtsi64x_sd" },
	intrin_desc{ .intrin_name = "_mm_cvtsi64x_si128" },
	intrin_desc{ .intrin_name = "_mm_cvttsd_si64x" },
	intrin_desc{ .intrin_name = "_mm_set_epi64" },
	intrin_desc{ .intrin_name = "_mm_set1_epi64" },
	intrin_desc{ .intrin_name = "_mm_slli_si128" }, // bslli
	intrin_desc{ .intrin_name = "_mm_srli_si128" }, // bsrli

	// sse3
	intrin_desc{
			.intrin_name = "_mm_addsub_pd",
			.func_name = "addsub",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_addsub_ps",
			.func_name = "addsub",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_hadd_pd",
			.func_name = "hadd",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_hadd_ps",
			.func_name = "hadd",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_hsub_pd",
			.func_name = "hsub",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 }, { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_hsub_ps",
			.func_name = "hsub",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 }, { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_lddqu_si128",
			.func_name = "lddqu",
			.return_opts{ topt::overloads, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::overloads, topt::const_ptr, topt::reg_to_cpp } },
	},
	intrin_desc{
			.intrin_name = "_mm_loaddup_pd",
			.func_name = "loaddup",
			.return_opts{ topt::f64, topt::ref, topt::to_last_param },
			.arg_opts{ { topt::keep } },
	},
	intrin_desc{
			.intrin_name = "_mm_movedup_pd",
			.func_name = "movedup",
			.return_opts{ topt::f64 },
			.arg_opts{ { topt::f64 } },
	},
	intrin_desc{
			.intrin_name = "_mm_movehdup_ps",
			.func_name = "movehdup",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 } },
	},
	intrin_desc{
			.intrin_name = "_mm_moveldup_ps",
			.func_name = "moveldup",
			.return_opts{ topt::f32 },
			.arg_opts{ { topt::f32 } },
	},

};
