name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # BUILD_TYPE: Release, Debug

jobs:
  windows_build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        # os: [windows-latest] # [ubuntu-20.04, ubuntu-18.04, windows-2019, windows-2016, macos-11, macos-10.15]
        build_type: [Release, Debug]
        build_arch: [x64, Win32]
        config:
          - { vs_ver: '"Visual Studio 16"', fea_ver: "" }
          - { vs_ver: '"Visual Studio 15"', fea_ver: "-DFEA_CPP17=On" }
          - { vs_ver: '"Visual Studio 14"', fea_ver: "-DFEA_CPP14=On" }

    steps:
    - name: Setup Git Line Endings
      run: |
        git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64' # optional, x86

    - name: Install Conan
      run: |
        python --version
        pip install conan
        conan user
        conan --version
        conan remote add bincrafters https://api.bintray.com/conan/conan/conan-center
        conan profile new default --detect

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cd ${{github.workspace}}
        mkdir build
        cd build
        cmake .. -G ${{ matrix.config.vs_ver }} -A ${{ matrix.build_arch }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ matrix.config.fea_ver }}

    - name: Build
      # Build your program with the given configuration
      run: |
        cd ${{github.workspace}}/build
        cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      # working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        cd ${{github.workspace}}/build
        ./bin/fea_libs_tests
        ./bin/fea_libs_nothrow_tests

